import {
  music,
  audioTurn,
  gameOver,
  winSlotsAndCoordinates,
} from "./extraData.js";
let turn = "X";
let isGameOver = false;
const checkBox = document.querySelectorAll(".boxtext");
const boxesCopy = document.querySelectorAll(".box");
// music.play();

// Decide turns
const changeTurn = () => {
  return turn === "X" ? "0" : "X";
};

const checkWin = () => {
  winSlotsAndCoordinates.forEach((slot) => {
    // If any winning slots matches, Winner Announced
    if (
      checkBox[slot[0]].innerText === checkBox[slot[1]].innerText &&
      checkBox[slot[2]].innerText === checkBox[slot[1]].innerText &&
      checkBox[slot[0]].innerText !== ""
    ) {
      document.getElementsByClassName("info")[0].innerText =
        checkBox[slot[1]].innerText + " Won the game!";
      isGameOver = !isGameOver;

      //Apply excited.gif
      document
        .querySelector(".imgbox")
        .getElementsByTagName("img")[0].style.width = "200px";
      gameOver.play();

      //Display succeess line
      document.querySelector(
        ".line"
      ).style.transform = `translate(${slot[3]}vw, ${slot[4]}vw) rotate(${slot[5]}deg)`;
      document.querySelector(".line").style.width = "20vw";
    }
  });
};

boxesCopy.forEach((element) => {
  const checkBox = element.querySelector(".boxtext");
  element.addEventListener("click", () => {
    if (checkBox.innerText === "") {
      // X and O registered in span tags
      checkBox.innerText = turn;
      turn = changeTurn();
      audioTurn.play();
      // Check winning combinations
      checkWin();
      if (!isGameOver) {
        document.getElementsByClassName("info")[0].innerText =
          "Turn for " + turn;
      }
    }
  });
});

document.getElementById("reset").addEventListener("click", () => {
  checkBox.forEach((slot) => {
    slot.innerText = "";
  });
  turn = "X";
  isGameOver = !isGameOver;
  document.querySelector(".line").style.width = "0vw";
  document.getElementsByClassName("info")[0].innerText = "Turn for " + turn;

  // Remove the excited.gif
  document.querySelector(".imgbox").getElementsByTagName("img")[0].style.width =
    "0px";
});

/*
Points to remember:
To iterate HTMLCollections we need Array.from(<array-name>).forEach(() => {}) generated by getElementsByClassName()
for NodeList, as an array the available built in methods works. generated by querySelectorAll()
*/
